### DISCUSSION TITLE
How to run cypress locally inside a local Docker?

### DISCUSSION THREAD

**Discussion by HackPoint** [cypress-io/cypress-realworld-app#733] [Q&A]
My Error:
```
cypress_1  | Cypress could not verify that this server is running:
cypress_1  | 
cypress_1  |   > http://localhost:3000
cypress_1  | 
cypress_1  | We are verifying this server because it has been configured as your `baseUrl`.
cypress_1  | 
cypress_1  | Cypress automatically waits until your server is accessible before running tests.
```

My docker-compose
```version: '3.2'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:5.0.0"
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    command: "--browser chrome"
    ports:
      - 3333:3000
    volumes:
      - ./:/e2e
```

My config
```{
  "baseUrl": "http://localhost:3000",
  "integrationFolder": "cypress/integration",
  "fileServerFolder": "dist",
  "viewportWidth": 1200,
  "viewportHeight": 1000,
  "chromeWebSecurity": true,
  "projectId": "3orb3g",
  "retries": {
    "runMode": 1,
    "openMode": 3
  }
}
```

**Comment by amirrustam** [comment]
The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

**Comment by HackPoint** [comment]
> The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

Thank you so much for the quick answer, but I can't create a runnable reproduction.

**Comment by HackPoint** [comment]
> The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

And After I changed the Cypress baseURL it's still give's me the same issue.

**Comment by amirrustam** [comment]
Any reason you're trying to run the project in Docker? Also, can you share why you are using cypress/included:5.0.0?

**Comment by jprealini** [comment]
@HackPoint Is your local app (the one you are testing) running also in a docker container?

@amirrustam I faced the same issue, but found that since I was hitting a dockerized app and api, I had to set my baseUrl and apiBaseUrl params to "http://webapp/" and "http://api" respectively, instead of localhost:4001 and localhost:3000, and run my dockerized Cypress with the param --network AppNetwork (which is the docker network my app and api are using)

```
version: '3'

networks:
  AppNetwork:
    external: true

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    hostname: api-container  
    ports:
       - 3000:80     
    networks:
    - AppNetwork
  webapp:
    build:
      context: ../      
      dockerfile: Dockerfile.WebApp
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    ports:
      - 4001:80
    networks:
    - AppNetwork 
```

http://webapp and http://api are the url's that docker exposes through the AppNetwork
