### ISSUE TITLE
CircleCI uses Node.js 14.17.5 not 16.16.0 for Windows tests

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-realworld-app#1354]
## Current behavior

The workflow [.circleci/config.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml) which runs using the [CircleCI pipeline](https://app.circleci.com/pipelines/github/cypress-io/cypress-realworld-app) shows that it runs in Node.js `14.17.5`.

```text
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 │ Cypress:        12.13.0                                                                        │
 │ Browser:        Electron 106 (headless)                                                        │
 │ Node Version:   v14.17.5 (C:\Program Files\nodejs\node.exe)                                    │
 │ Specs:          7 found (auth.spec.ts, bankaccounts.spec.ts, new-transaction.spec.ts, notifica │
 │                 tions.spec.ts, transaction-feeds.spec.ts, transaction-view.spec.ts, user-setti │
 │                 ngs.spec.ts)                                                                   │
 │ Searched:       C:\Users\circleci\project\cypress\tests\ui\*                                   │
 │ Params:         Tag: false, Group: UI - Electron - Windows, Parallel: true                     │
 │ Run URL:        https://cloud.cypress.io/projects/7s5okt/runs/6046                             │
 └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Desired behavior

1. The Windows CI tests should use the version `16.16.0` of Node.js as defined in [.node-version](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.node-version).

https://github.com/cypress-io/cypress-realworld-app/blob/761846aa99042f8b320290966d733e579944db8c/.node-version#LL1

2. Addtionally, since Node.js 14.x passed into [end-of-life status](https://github.com/nodejs/release#release-schedule) on Apr 30, 2023, it is no longer a version which should be actively used in this example repository.

## Analysis

The workflow [.circleci/config.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml) uses

```yml
orbs:
  cypress: cypress-io/cypress@3.1.1
  codecov: codecov/codecov@1.2.3 #
  win: circleci/windows@4.1.1
```

and

```yml
jobs:
  setup_project_and_cypress_windows:
    executor:
      # executor comes from the "windows" orb
      name: win/default
      shell: bash.exe
      size: large
```

## Suggestion

Modify the choice and setup of CircleCI to provide the Node.js `16.16.0` version for testing on Windows Server.
